language: node_js
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
node_js:
  - "lts/*"
  - "node"
  - "6"
script: 
  - npm run build
  - npm test
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT